# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/chris/OneDrive/Desktop/SummerOfBrain

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/chris/OneDrive/Desktop/SummerOfBrain

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/chris/OneDrive/Desktop/SummerOfBrain/CMakeFiles /mnt/c/Users/chris/OneDrive/Desktop/SummerOfBrain/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/chris/OneDrive/Desktop/SummerOfBrain/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SummerOfBrain

# Build rule for target.
SummerOfBrain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SummerOfBrain
.PHONY : SummerOfBrain

# fast build rule for target.
SummerOfBrain/fast:
	$(MAKE) -f CMakeFiles/SummerOfBrain.dir/build.make CMakeFiles/SummerOfBrain.dir/build
.PHONY : SummerOfBrain/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f Testing/lib/googletest-master/googlemock/CMakeFiles/gmock_main.dir/build.make Testing/lib/googletest-master/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f Testing/lib/googletest-master/googlemock/CMakeFiles/gmock.dir/build.make Testing/lib/googletest-master/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f Testing/lib/googletest-master/googletest/CMakeFiles/gtest_main.dir/build.make Testing/lib/googletest-master/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f Testing/lib/googletest-master/googletest/CMakeFiles/gtest.dir/build.make Testing/lib/googletest-master/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

ChainOfResponsibility/ChainNode.o: ChainOfResponsibility/ChainNode.cpp.o

.PHONY : ChainOfResponsibility/ChainNode.o

# target to build an object file
ChainOfResponsibility/ChainNode.cpp.o:
	$(MAKE) -f CMakeFiles/SummerOfBrain.dir/build.make CMakeFiles/SummerOfBrain.dir/ChainOfResponsibility/ChainNode.cpp.o
.PHONY : ChainOfResponsibility/ChainNode.cpp.o

ChainOfResponsibility/ChainNode.i: ChainOfResponsibility/ChainNode.cpp.i

.PHONY : ChainOfResponsibility/ChainNode.i

# target to preprocess a source file
ChainOfResponsibility/ChainNode.cpp.i:
	$(MAKE) -f CMakeFiles/SummerOfBrain.dir/build.make CMakeFiles/SummerOfBrain.dir/ChainOfResponsibility/ChainNode.cpp.i
.PHONY : ChainOfResponsibility/ChainNode.cpp.i

ChainOfResponsibility/ChainNode.s: ChainOfResponsibility/ChainNode.cpp.s

.PHONY : ChainOfResponsibility/ChainNode.s

# target to generate assembly for a file
ChainOfResponsibility/ChainNode.cpp.s:
	$(MAKE) -f CMakeFiles/SummerOfBrain.dir/build.make CMakeFiles/SummerOfBrain.dir/ChainOfResponsibility/ChainNode.cpp.s
.PHONY : ChainOfResponsibility/ChainNode.cpp.s

ChainOfResponsibility/ChainOperationManager.o: ChainOfResponsibility/ChainOperationManager.cpp.o

.PHONY : ChainOfResponsibility/ChainOperationManager.o

# target to build an object file
ChainOfResponsibility/ChainOperationManager.cpp.o:
	$(MAKE) -f CMakeFiles/SummerOfBrain.dir/build.make CMakeFiles/SummerOfBrain.dir/ChainOfResponsibility/ChainOperationManager.cpp.o
.PHONY : ChainOfResponsibility/ChainOperationManager.cpp.o

ChainOfResponsibility/ChainOperationManager.i: ChainOfResponsibility/ChainOperationManager.cpp.i

.PHONY : ChainOfResponsibility/ChainOperationManager.i

# target to preprocess a source file
ChainOfResponsibility/ChainOperationManager.cpp.i:
	$(MAKE) -f CMakeFiles/SummerOfBrain.dir/build.make CMakeFiles/SummerOfBrain.dir/ChainOfResponsibility/ChainOperationManager.cpp.i
.PHONY : ChainOfResponsibility/ChainOperationManager.cpp.i

ChainOfResponsibility/ChainOperationManager.s: ChainOfResponsibility/ChainOperationManager.cpp.s

.PHONY : ChainOfResponsibility/ChainOperationManager.s

# target to generate assembly for a file
ChainOfResponsibility/ChainOperationManager.cpp.s:
	$(MAKE) -f CMakeFiles/SummerOfBrain.dir/build.make CMakeFiles/SummerOfBrain.dir/ChainOfResponsibility/ChainOperationManager.cpp.s
.PHONY : ChainOfResponsibility/ChainOperationManager.cpp.s

ChainOfResponsibility/Foo.o: ChainOfResponsibility/Foo.cpp.o

.PHONY : ChainOfResponsibility/Foo.o

# target to build an object file
ChainOfResponsibility/Foo.cpp.o:
	$(MAKE) -f CMakeFiles/SummerOfBrain.dir/build.make CMakeFiles/SummerOfBrain.dir/ChainOfResponsibility/Foo.cpp.o
.PHONY : ChainOfResponsibility/Foo.cpp.o

ChainOfResponsibility/Foo.i: ChainOfResponsibility/Foo.cpp.i

.PHONY : ChainOfResponsibility/Foo.i

# target to preprocess a source file
ChainOfResponsibility/Foo.cpp.i:
	$(MAKE) -f CMakeFiles/SummerOfBrain.dir/build.make CMakeFiles/SummerOfBrain.dir/ChainOfResponsibility/Foo.cpp.i
.PHONY : ChainOfResponsibility/Foo.cpp.i

ChainOfResponsibility/Foo.s: ChainOfResponsibility/Foo.cpp.s

.PHONY : ChainOfResponsibility/Foo.s

# target to generate assembly for a file
ChainOfResponsibility/Foo.cpp.s:
	$(MAKE) -f CMakeFiles/SummerOfBrain.dir/build.make CMakeFiles/SummerOfBrain.dir/ChainOfResponsibility/Foo.cpp.s
.PHONY : ChainOfResponsibility/Foo.cpp.s

Testing/ChainOfResponsibility/ChainNodeTests.o: Testing/ChainOfResponsibility/ChainNodeTests.cpp.o

.PHONY : Testing/ChainOfResponsibility/ChainNodeTests.o

# target to build an object file
Testing/ChainOfResponsibility/ChainNodeTests.cpp.o:
	$(MAKE) -f CMakeFiles/SummerOfBrain.dir/build.make CMakeFiles/SummerOfBrain.dir/Testing/ChainOfResponsibility/ChainNodeTests.cpp.o
.PHONY : Testing/ChainOfResponsibility/ChainNodeTests.cpp.o

Testing/ChainOfResponsibility/ChainNodeTests.i: Testing/ChainOfResponsibility/ChainNodeTests.cpp.i

.PHONY : Testing/ChainOfResponsibility/ChainNodeTests.i

# target to preprocess a source file
Testing/ChainOfResponsibility/ChainNodeTests.cpp.i:
	$(MAKE) -f CMakeFiles/SummerOfBrain.dir/build.make CMakeFiles/SummerOfBrain.dir/Testing/ChainOfResponsibility/ChainNodeTests.cpp.i
.PHONY : Testing/ChainOfResponsibility/ChainNodeTests.cpp.i

Testing/ChainOfResponsibility/ChainNodeTests.s: Testing/ChainOfResponsibility/ChainNodeTests.cpp.s

.PHONY : Testing/ChainOfResponsibility/ChainNodeTests.s

# target to generate assembly for a file
Testing/ChainOfResponsibility/ChainNodeTests.cpp.s:
	$(MAKE) -f CMakeFiles/SummerOfBrain.dir/build.make CMakeFiles/SummerOfBrain.dir/Testing/ChainOfResponsibility/ChainNodeTests.cpp.s
.PHONY : Testing/ChainOfResponsibility/ChainNodeTests.cpp.s

Testing/ChainOfResponsibility/ChainOperationManagerTests.o: Testing/ChainOfResponsibility/ChainOperationManagerTests.cpp.o

.PHONY : Testing/ChainOfResponsibility/ChainOperationManagerTests.o

# target to build an object file
Testing/ChainOfResponsibility/ChainOperationManagerTests.cpp.o:
	$(MAKE) -f CMakeFiles/SummerOfBrain.dir/build.make CMakeFiles/SummerOfBrain.dir/Testing/ChainOfResponsibility/ChainOperationManagerTests.cpp.o
.PHONY : Testing/ChainOfResponsibility/ChainOperationManagerTests.cpp.o

Testing/ChainOfResponsibility/ChainOperationManagerTests.i: Testing/ChainOfResponsibility/ChainOperationManagerTests.cpp.i

.PHONY : Testing/ChainOfResponsibility/ChainOperationManagerTests.i

# target to preprocess a source file
Testing/ChainOfResponsibility/ChainOperationManagerTests.cpp.i:
	$(MAKE) -f CMakeFiles/SummerOfBrain.dir/build.make CMakeFiles/SummerOfBrain.dir/Testing/ChainOfResponsibility/ChainOperationManagerTests.cpp.i
.PHONY : Testing/ChainOfResponsibility/ChainOperationManagerTests.cpp.i

Testing/ChainOfResponsibility/ChainOperationManagerTests.s: Testing/ChainOfResponsibility/ChainOperationManagerTests.cpp.s

.PHONY : Testing/ChainOfResponsibility/ChainOperationManagerTests.s

# target to generate assembly for a file
Testing/ChainOfResponsibility/ChainOperationManagerTests.cpp.s:
	$(MAKE) -f CMakeFiles/SummerOfBrain.dir/build.make CMakeFiles/SummerOfBrain.dir/Testing/ChainOfResponsibility/ChainOperationManagerTests.cpp.s
.PHONY : Testing/ChainOfResponsibility/ChainOperationManagerTests.cpp.s

Testing/RunTests.o: Testing/RunTests.cpp.o

.PHONY : Testing/RunTests.o

# target to build an object file
Testing/RunTests.cpp.o:
	$(MAKE) -f CMakeFiles/SummerOfBrain.dir/build.make CMakeFiles/SummerOfBrain.dir/Testing/RunTests.cpp.o
.PHONY : Testing/RunTests.cpp.o

Testing/RunTests.i: Testing/RunTests.cpp.i

.PHONY : Testing/RunTests.i

# target to preprocess a source file
Testing/RunTests.cpp.i:
	$(MAKE) -f CMakeFiles/SummerOfBrain.dir/build.make CMakeFiles/SummerOfBrain.dir/Testing/RunTests.cpp.i
.PHONY : Testing/RunTests.cpp.i

Testing/RunTests.s: Testing/RunTests.cpp.s

.PHONY : Testing/RunTests.s

# target to generate assembly for a file
Testing/RunTests.cpp.s:
	$(MAKE) -f CMakeFiles/SummerOfBrain.dir/build.make CMakeFiles/SummerOfBrain.dir/Testing/RunTests.cpp.s
.PHONY : Testing/RunTests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... SummerOfBrain"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... gmock_main"
	@echo "... gmock"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... ChainOfResponsibility/ChainNode.o"
	@echo "... ChainOfResponsibility/ChainNode.i"
	@echo "... ChainOfResponsibility/ChainNode.s"
	@echo "... ChainOfResponsibility/ChainOperationManager.o"
	@echo "... ChainOfResponsibility/ChainOperationManager.i"
	@echo "... ChainOfResponsibility/ChainOperationManager.s"
	@echo "... ChainOfResponsibility/Foo.o"
	@echo "... ChainOfResponsibility/Foo.i"
	@echo "... ChainOfResponsibility/Foo.s"
	@echo "... Testing/ChainOfResponsibility/ChainNodeTests.o"
	@echo "... Testing/ChainOfResponsibility/ChainNodeTests.i"
	@echo "... Testing/ChainOfResponsibility/ChainNodeTests.s"
	@echo "... Testing/ChainOfResponsibility/ChainOperationManagerTests.o"
	@echo "... Testing/ChainOfResponsibility/ChainOperationManagerTests.i"
	@echo "... Testing/ChainOfResponsibility/ChainOperationManagerTests.s"
	@echo "... Testing/RunTests.o"
	@echo "... Testing/RunTests.i"
	@echo "... Testing/RunTests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

