/**
 *      @file AllDSSynapses.h
 *
 *      @brief A container of all DS synapse data
 *
 * @authors Aaron Oziel, Sean Blackbourn
 *
 *  The container holds synapse parameters of all synapses. 
 *  Each kind of synapse parameter is stored in a 2D array. Each item in the first 
 *  dimention of the array corresponds with each neuron, and each item in the second
 *  dimension of the array corresponds with a synapse parameter of each synapse of the neuron. 
 *  Bacause each neuron owns different number of synapses, the number of synapses 
 *  for each neuron is stored in a 1D array, synapse_counts.
 *
 *  For CUDA implementation, we used another structure, AllDSSynapsesDevice, where synapse
 *  parameters are stored in 1D arrays instead of 2D arrays, so that device functions
 *  can access these data less latency. When copying a synapse parameter, P[i][j],
 *  from host to device, it is stored in P[i * max_synapses_per_neuron + j] in 
 *  AllDSSynapsesDevice structure.
 *
 *  The latest implementation uses the identical data struture between host and CUDA;
 *  that is, synapse parameters are stored in a 1D array, so we don't need conversion
 *  when copying data between host and device memory.
 *
 * Phenomenological model of frequency-dependent synapses exibit dynamics that include
 * activity-dependent facilitation and depression (Tsodyks and Markram 1997, Tsodyks et al. 1998).
 * The model has two state variables: \f$r\f$ (the fraction of available synaptic efficacy), and
 * \f$u\f$ (the running value of utilization of synaptic efficacy).
 *
 * \f[
 *  r_{n+1} = r_n \cdot (1-u_{n+1}) \cdot \mathrm{e}^{-\frac{\Delta t}{\tau_{rec}}} +
 *  1 - \mathrm{e}^{-\frac{\Delta t}{\tau_{rec}}}
 * \f]
 *
 * \f[
 * \f]
 *
 * where \f$\Delta t\f$ is the time interval between nth and (n + 1)th AP,
 * the two time constants \f$\tau_{rec}\f$ and \f$\tau_{facil}\f$ govern recovery from depression,
 * and facilitation after a spike, and \f$U\f$ is utilization of synaptic efficacy (Markram et al. 1998).
 *
 * The synaptic response that is generated by any AP in a train is therefore given by:
 * \f[
 *  EPSP_n = A \cdot r_n \cdot u_n
 * \f]
 */
#pragma once

#include "AllSpikingSynapses.h"

struct AllDSSynapsesDeviceProperties;

class AllDSSynapses : public AllSpikingSynapses {
public:
   AllDSSynapses();

   AllDSSynapses(const int numNeurons, const int maxSynapses);

   virtual ~AllDSSynapses();

   static IAllSynapses *Create() { return new AllDSSynapses(); }

   ///  Setup the internal structure of the class (allocate memories and initialize them).
   virtual void setupSynapses();

   ///  Reset time varying state vars and recompute decay.
   ///
   ///  @param  iSyn     Index of the synapse to set.
   ///  @param  deltaT   Inner simulation step duration
   virtual void resetSynapse(const BGSIZE iSyn, const BGFLOAT deltaT);

   ///  Prints out all parameters to logging file.
   ///  Registered to OperationManager as Operation::printParameters
   virtual void printParameters() const;

   ///  Create a Synapse and connect it to the model.
   ///
   ///  @param  iSyn        Index of the synapse to set.
   ///  @param  srcNeuron     Coordinates of the source Neuron.
   ///  @param  destNeuron        Coordinates of the destination Neuron.
   ///  @param  sumPoint   Summation point address.
   ///  @param  deltaT      Inner simulation step duration.
   ///  @param  type        Type of the Synapse to create.
   virtual void createSynapse(const BGSIZE iSyn, int srcNeuron, int destNeuron, BGFLOAT *sumPoint, const BGFLOAT deltaT,
                              synapseType type);

   ///  Prints SynapsesProps data to console.
   virtual void printSynapsesProps() const;

protected:
   ///  Setup the internal structure of the class (allocate memories and initialize them).
   ///
   ///  @param  numNeurons   Total number of neurons in the network.
   ///  @param  maxSynapses  Maximum number of synapses per neuron.
   virtual void setupSynapses(const int numNeurons, const int maxSynapses);

   ///  Sets the data for Synapse to input's data.
   ///
   ///  @param  input  istream to read from.
   ///  @param  iSyn   Index of the synapse to set.
   virtual void readSynapse(istream &input, const BGSIZE iSyn);

   ///  Write the synapse data to the stream.
   ///
   ///  @param  output  stream to print out to.
   ///  @param  iSyn    Index of the synapse to print out.
   virtual void writeSynapse(ostream &output, const BGSIZE iSyn) const;

#if defined(USE_GPU)
   public:
       ///  Allocate GPU memories to store all synapses' states,
       ///  and copy them from host to GPU memory.
       ///
       ///  @param  allSynapsesDevice  GPU address of the allSynapses struct on device memory.
       virtual void allocSynapseDeviceStruct( void** allSynapsesDevice);

       ///  Allocate GPU memories to store all synapses' states,
       ///  and copy them from host to GPU memory.
       ///
       ///  @param  allSynapsesDevice     GPU address of the allSynapses struct on device memory.
       ///  @param  numNeurons            Number of neurons.
       ///  @param  maxSynapsesPerNeuron  Maximum number of synapses per neuron.
       virtual void allocSynapseDeviceStruct( void** allSynapsesDevice, int numNeurons, int maxSynapsesPerNeuron);

       ///  Delete GPU memories.
       ///
       ///  @param  allSynapsesDevice     GPU address of the allSynapses struct on device memory.
       virtual void deleteSynapseDeviceStruct( void* allSynapsesDevice );

       ///  Copy all synapses' data from host to device.
       ///
       ///  @param  allSynapsesDevice  GPU address of the allSynapses struct on device memory.
       virtual void copySynapseHostToDevice( void* allSynapsesDevice );

       ///  Copy all synapses' data from host to device.
       ///
       ///  @param  allSynapsesDevice     GPU address of the allSynapses struct on device memory.
       ///  @param  numNeurons            Number of neurons.
       ///  @param  maxSynapsesPerNeuron  Maximum number of synapses per neuron.
       virtual void copySynapseHostToDevice( void* allSynapsesDevice, int numNeurons, int maxSynapsesPerNeuron );

       ///  Copy all synapses' data from device to host.
       ///
       ///  @param  allSynapsesDevice  GPU address of the allSynapses struct on device memory.
       virtual void copySynapseDeviceToHost( void* allSynapsesDevice);

       ///  Set synapse class ID defined by enumClassSynapses for the caller's Synapse class.
       ///  The class ID will be set to classSynapses_d in device memory,
       ///  and the classSynapses_d will be referred to call a device function for the
       ///  particular synapse class.
       ///  Because we cannot use virtual function (Polymorphism) in device functions,
       ///  we use this scheme.
       ///  Note: we used to use a function pointer; however, it caused the growth_cuda crash
       ///  (see issue#137).
       virtual void setSynapseClassID();

       ///  Prints GPU SynapsesProps data.
       ///
       ///  @param  allSynapsesDeviceProps   GPU address of the corresponding SynapsesDeviceProperties struct on device memory.
       virtual void printGPUSynapsesProps(void* allSynapsesDeviceProps) const;

   protected:
       ///  Allocate GPU memories to store all synapses' states,
       ///  and copy them from host to GPU memory.
       ///  (Helper function of allocSynapseDeviceStruct)
       ///
       ///  @param  allSynapsesDevice     GPU address of the allSynapses struct on device memory.
       ///  @param  numNeurons            Number of neurons.
       ///  @param  maxSynapsesPerNeuron  Maximum number of synapses per neuron.
       void allocDeviceStruct( AllDSSynapsesDeviceProperties &allSynapses, int numNeurons, int maxSynapsesPerNeuron );

       ///  Delete GPU memories.
       ///  (Helper function of deleteSynapseDeviceStruct)
       ///
       ///  @param  allSynapsesDeviceProps  GPU address of the allSynapses struct on device memory.
       void deleteDeviceStruct( AllDSSynapsesDeviceProperties& allSynapsesDeviceProps );

       ///  Copy all synapses' data from host to device.
       ///  (Helper function of copySynapseHostToDevice)
       ///
       ///  @param  allSynapsesDevice      GPU address of the allSynapses struct on device memory.
       ///  @param  allSynapsesDeviceProps GPU address of the AllDSSSynapses struct on device memory.
       ///  @param  numNeurons             Number of neurons.
       ///  @param  maxSynapsesPerNeuron   Maximum number of synapses per neuron.
       void copyHostToDevice( void* allSynapsesDevice, AllDSSynapsesDeviceProperties& allSynapsesDeviceProps, int numNeurons, int maxSynapsesPerNeuron );

       ///  Copy all synapses' data from device to host.
       ///  (Helper function of copySynapseDeviceToHost)
       ///
       ///  @param  allSynapsesDeviceProps  GPU address of the allSynapses struct on device memory.
       void copyDeviceToHost( AllDSSynapsesDeviceProperties& allSynapsesDeviceProps);
#else // !defined(USE_GPU)
protected:
   ///  Calculate the post synapse response after a spike.
   ///
   ///  @param  iSyn        Index of the synapse to set.
   ///  @param  deltaT      Inner simulation step duration.
   virtual void changePSR(const BGSIZE iSyn, const BGFLOAT deltaT);

#endif // defined(USE_GPU)
public:

   ///  The time of the last spike.
   uint64_t *lastSpike_;

   ///  The time varying state variable \f$r\f$ for depression.
   BGFLOAT *r_;

   ///  The time varying state variable \f$u\f$ for facilitation.
   BGFLOAT *u_;

   ///  The time constant of the depression of the dynamic synapse [range=(0,10); units=sec].
   BGFLOAT *D_;

   ///  The use parameter of the dynamic synapse [range=(1e-5,1)].
   BGFLOAT *U_;

   ///  The time constant of the facilitation of the dynamic synapse [range=(0,10); units=sec].
   BGFLOAT *F_;
};

#if defined(USE_GPU)
struct AllDSSynapsesDeviceProperties : public AllSpikingSynapsesDeviceProperties
{
        ///  The time of the last spike.
        uint64_t *lastSpike_;

        ///  The time varying state variable \f$r\f$ for depression.
        BGFLOAT *r_;
        
        ///  The time varying state variable \f$u\f$ for facilitation.
        BGFLOAT *u_;
        
        ///  The time constant of the depression of the dynamic synapse [range=(0,10); units=sec].
        BGFLOAT *D_;
        
        ///  The use parameter of the dynamic synapse [range=(1e-5,1)].
        BGFLOAT *U_;

        ///  The time constant of the facilitation of the dynamic synapse [range=(0,10); units=sec].
        BGFLOAT *F_;
};
#endif // defined(USE_GPU)

