@startuml topLevelFlow

title Graphitti General Program Flow

Core -> ParamContainer **: Parse Command Line
activate ParamContainer
note right
    Config File
    Deserialize File
    Serealize File
    Stimulus File
end note

Core -> Simulator: Set File Names
Simulator -> ParamContainer: Get File Names
ParamContainer -> Simulator: File Names
deactivate ParamContainer

Core -> ParameterManager: Load Parameter File
ParameterManager -> Simulator: Get Config File Name
Simulator -> ParameterManager: Config File Name
Core -> Simulator: Load Parameters
Simulator -> ParameterManager: Get parameters from XML
ParameterManager -> Simulator: Parameters
note right
    width_, height_, epochDuration_,
    numEpochs_, maxFiringRate_,
    maxEdgesPerVertex_, RNG, etc.
end note

Core -> Simulator: Instantiate Simulator Objects
note right
    Details are in a separate
    sequence diagram.
end note

Core -> OperationManager: Register Graph Properties
note right
    Ask all objects to register their Graph properties
end note

Core -> GraphManager: Read Graph

' Expand in a separate diagram
Core -> OperationManager: Load Parameters
note right
    Runs loadParameters method for
    each instantiated object.
    Methods are registered to
    OperationManager on instantiation.
end note

Core -> Simulator: Setup
note right
    Details are in a separate
    sequence diagram.
end note


opt if serialized file name available
    Core -> Serializer: Deserialize file
end

Core -> Simulator: Simulate
note right
    Details are in a separate
    sequence diagram.
end note

opt if serializtion file available
    Core -> Serializer: Serialize Synapses
end

Core -> Simulator: Finish
Simulator -> Model: Clean up model resources
Core -> Recorder: Terminate Recording
Core -> Core: Exit program

@enduml
