name: Check for Code Style Violations
on:
  push:
    paths:
      - '**.cpp'
      - '**.h'
    branches:
      - master
  pull_request:
    paths:
      - '**.cpp'
      - '**.h'
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Install missing software on ubuntu
        run: sudo apt-get install clang-format

      - name: Code format check
        run: |
          echo "*** running clang-format to check for style violations"
          
          # Find and print the .clang-format file
          dir="$PWD"
          while [ "$dir" != "/" ]; do
            if [ -f "$dir/.clang-format" ]; then
              echo "Found .clang-format at: $dir/.clang-format"
              cat "$dir/.clang-format"
              break
            fi
            dir=$(dirname "$dir")
          done
          
          # Run the style check
          clang-format --dry-run --Werror --style=file `find . -type f \( -iname "*.cpp" -or -iname "*.h" \) ! -path "./Testing/lib/*" ! -path "./ThirdParty/*" ! -path "./docs/*"`
