name: Github Pages

on:
  schedule:
    # Triggers at the end of the day on the 1st of every month
    - cron: '0 0 1 * *'
  workflow_dispatch:
    # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Generate Doxygen
        uses: mattnotmitt/doxygen-action@v1
        with:
          doxyfile-path: docs/Doxygen/Doxyfile
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          destination_dir: docs
          force_orphan: true
