name: Generate PlantUML Diagrams
on:
  push:
    paths:
      - '**.puml'
    branches:
      - master
      - plantUML-Diagrams
  pull_request:
    paths:
      - '**.puml'
    branches:
      - master
      - plantUML-Diagrams
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
        UML_FILES: ".puml"
    steps:
      - name: Checkout Source 
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get all UML files
        id: getfile
        run: |
          #List the .puml files in the working directory
          find . -name '*.puml' \
          | awk  'BEGIN { printf "::set-output name=files::" }
          {
            # only process puml files
            # do not try to process our theme or custom config
            if ( $1 ~ /\.puml$/ && $1 !~ /(theme|config)\.puml$/ )
            {
              # only print the file name and strip newlines for spaces
              printf "%s ", $1
            }
          }
          END { print "" } # ensure we do print a newline at the end
          '
      - name: UML files considered echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}

      # - name: Generate SVG Diagrams
      #   uses: UWB-Biocomputing/plantuml-github-action@main
      #   with:
      #       args: -o "diagrams" -v -tsvg ${{ steps.getfile.outputs.files }}
      # - name: Generate PNG Diagrams
      #   uses: UWB-Biocomputing/plantuml-github-action@main
      #   with:
      #       args: -o "diagrams" -v -tpng ${{ steps.getfile.outputs.files }}

      - name: Generate SVG Diagrams
        uses: rotaract/plantuml-action@v1
        with:
          pattern: "docs/**.puml"
          format: svg ${{ steps.getfile.outputs.files }}
      - name: Generate PNG Diagrams
        uses: rotaract/plantuml-action@v1
        with:
          pattern: "docs/**.puml"
          format: png ${{ steps.getfile.outputs.files }}

      - name: Push Local Changes
        uses:  stefanzweifel/git-auto-commit-action@v4 
        with:
          commit_message: "Generate SVG and PNG images for PlantUML diagrams" 
          branch: ${{ github.head_ref }}
