@startuml RecorderClassDiagram





/' Objects '/

class Hdf5GrowthRecorder {
	+Hdf5GrowthRecorder()
	+~Hdf5GrowthRecorder()
	#radiiHistory_ : BGFLOAT*
	#ratesHistory_ : BGFLOAT*
	#dataSetRadiiHist_ : DataSet
	#dataSetRatesHist_ : DataSet
	+{static} Create() : Recorder*
	+compileHistories(AllVertices& neurons) : void
	+getValues() : void
	#initDataSet() : void
	+initDefaultValues() : void
	+initValues() : void
	+printParameters() : void
	+term() : void
	#writeRadiiRates() : void
}


class Hdf5Recorder {
	+Hdf5Recorder()
	#dataSetNeuronThresh_ : DataSet
	#dataSetNeuronTypes_ : DataSet
	#dataSetProbedNeurons_ : DataSet
	#dataSetSimulationEndTime_ : DataSet
	#dataSetSpikesHist_ : DataSet
	#dataSetSpikesProbedNeurons_ : DataSet
	#dataSetStarterNeurons_ : DataSet
	#dataSetTsim_ : DataSet
	#dataSetXloc_ : DataSet
	#dataSetYloc_ : DataSet
	#resultOut_ : H5File
	+{static} Create() : Recorder*
	#offsetSpikesProbedNeurons_ : hsize_t*
	#spikesHistory_ : int*
	#spikesProbedNeurons_ : vector<uint64_t>*
	+compileHistories(AllVertices& neurons) : void
	#getStarterNeuronMatrix(VectorMatrix& matrix, const bool* starterMap) : void
	+getValues() : void
	+init() : void
	#initDataSet() : void
	+initDefaultValues() : void
	+initValues() : void
	+printParameters() : void
	+saveSimData(const AllVertices& neurons) : void
	+term() : void
}


abstract class Recorder {
	+~Recorder()
	#fileLogger_ : log4cplus::Logger
	#resultFileName_ : string
	+{abstract} compileHistories(AllVertices& vertices) : void
	#{abstract} getStarterNeuronMatrix(VectorMatrix& matrix, const bool* starterMap) : void
	+{abstract} getValues() : void
	+{abstract} init() : void
	+{abstract} initDefaultValues() : void
	+{abstract} initValues() : void
	+{abstract} printParameters() : void
	+{abstract} saveSimData(const AllVertices& vertices) : void
	+{abstract} term() : void
	+{abstract} registerVariable(const string &varName, RecordableBase &recordVar, UpdatedType variableType) : void
	+{abstract} registerVariable(const string &varName, vector<RecordableBase *> &recordVars) : void
}


class RecorderFactory {
	-RecorderFactory()
	+~RecorderFactory()
	-invokeCreateFunction(const string& className) : Recorder*
	+{static} getInstance() : RecorderFactory*
	-createFunctions : RecorderFunctionMap
	+createRecorder(const string& className) : shared_ptr<Recorder>
	-recorderInstance : shared_ptr<Recorder>
	-registerClass(const string& className, CreateFunction function) : void
}


class XmlRecorder {
	+XmlRecorder()
	+{static} Create() : Recorder*
	#variableTable_ : vector<singleVariableInfo>
	#resultOut_ : ofstream
	+compileHistories() : void
	+init() : void
	+printParameters() : void
	+saveSimData() : void
	+term() : void
	+registerVariable(const string &varName, RecordableBase &recordVar, UpdatedType variableType) : void
	+registerVariable(const string &varName, vector<RecordableBase *> &recordVars) : void
	
	/' methods only used for unit test 
	+XmlRecorder(string fileName_)
	+getVariableName(int numIndex) const : const string&
	+getSingleVariable(int numIndex) const : &RecordableBase
	+getHistory() const : const &vector<variant<uint64_t, bool, int, BGFLOAT>>
	'/
}

struct singleVariableInfo {
	#variableName_ : string
	#variableLocation_ : RecordableBase&
	#variableHistory_ : vector<variant<uint64_t, bool, int, BGFLOAT>
	#dataType_ : string
	#variableType: UpdatedType
	+singleVariableInfo(string name, RecordableBase &location)
	+captureData()
}



/' Inheritance relationships '/

.Hdf5Recorder <|-- .Hdf5GrowthRecorder


.Recorder <|-- .Hdf5Recorder


.Recorder <|-- .XmlRecorder


/' Aggregation relationships '/

.RecorderFactory *-- .Recorder

/' Composition relationships '/

.XmlRecorder *-- .singleVariableInfo




/' Nested objects '/



@enduml
